### ISSUE TITLE
 org.apache.rocketmq.console.exception.ServiceException: This date have't data!

### ISSUE THREAD

**Issue by qq727127158** [foxiswho/docker-rocketmq#3]
如题，打开8180服务时后台一直报这个错误

**Comment by qq727127158** [comment]
[2019-05-09 20:59:40.355] ERROR op=global_exception_handler_print_error


org.apache.rocketmq.console.exception.ServiceException: This date have't data!


	at org.apache.rocketmq.console.service.impl.DashboardCollectServiceImpl.getTopicCache(DashboardCollectServiceImpl.java:150)


	at org.apache.rocketmq.console.service.impl.DashboardServiceImpl.queryTopicData(DashboardServiceImpl.java:55)


	at org.apache.rocketmq.console.controller.DashboardController.topic(DashboardController.java:49)


	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.lang.reflect.Method.invoke(Method.java:498)


	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)


	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)


	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)


	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)


	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)


	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)


	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)


	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)


	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)


	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)


	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)


	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)


	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)


	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)


	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)


	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)


	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)


	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)


	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)


	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)


	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)


	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)


	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)


	at java.lang.Thread.run(Thread.java:745)

**Comment by foxiswho** [comment]
没遇到你的问题。估计配置问题。你到官方看看

**Comment by mengxiaofei007** [comment]
我也遇到这种问题了 为什么是没有呢

**Comment by mengxiaofei007** [comment]
> 没遇到你的问题。估计配置问题。你到官方看看

我也遇到这种问题了 为什么是没有呢
