### ISSUE TITLE
java.io.FileNotFoundException: /etc/rocketmq/broker.conf (Is a directory)问题解决办法

### ISSUE THREAD

**Issue by wujixian** [foxiswho/docker-rocketmq#37]
当执行./start.sh时候，broker一直启动失败 报错，如下：
java.io.FileNotFoundException: /etc/rocketmq/broker.conf (Is a directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.apache.rocketmq.broker.BrokerStartup.createBrokerController(BrokerStartup.java:128)
        at org.apache.rocketmq.broker.BrokerStartup.main(BrokerStartup.java:58)

原因是 要修改一下docker-compose的内容：
![image](https://user-images.githubusercontent.com/11608170/155476474-d6c4852c-82bc-4345-b8ea-38320f19ee5f.png)
修改之后 调用./start.sh 然后就会看到启动成功，如下

![image](https://user-images.githubusercontent.com/11608170/155475650-a01e5cae-4c4e-4e39-a431-3ccf6ad84798.png)

亲测有效

**Comment by wujixian** [comment]
我是修改完后 ，是直接执行的  docker-compose up -d 并没有再执行 ./start.sh，因为我的store和logs路径已经变了

**Comment by foxiswho** [comment]
在liunx/mac下 系统支持当前目录 自动映射 成绝对路径,不需要写成 绝对路径
==========
因为宿主机的 broker.conf 文件 跟 容器内 rocketmq-4.x.x 目录下 conf下broker.conf文件 没有任何关系，
在 rmqbroker 中，指定 mqbroker 启动使用指定 宿主机的broker 配置文件，所以任何位置都可以

把本地 broker.conf 配置文件映射的容器内，其中 rmqbroker 有一个命令 指向自定义的目录位置
command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true"]
===========
