### ISSUE TITLE
镜像是可以运行的 但是出现了RemotingTooMuchRequestException这个异常

### ISSUE THREAD

**Issue by SliTaz** [foxiswho/docker-rocketmq#7]
RocketMQLog:WARN No appenders could be found for logger (io.netty.util.internal.InternalThreadLocalMap).
RocketMQLog:WARN Please initialize the logger system properly.
Exception in thread "main" org.apache.rocketmq.remoting.exception.RemotingTooMuchRequestException: sendDefaultImpl call timeout
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:640)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1310)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1256)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:339)
	at Test.main(Test.java:28)

**Comment by SliTaz** [comment]
解决了  楼主真棒

**Comment by eltonbfw** [comment]
> 解决了 楼主真棒

咋解决de ?

**Comment by vicoqi** [comment]
咋解决的？
